# Generated by Django 4.2.5 on 2023-09-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
                ('address', models.TextField(max_length=100)),
                ('call_us', models.CharField(max_length=20)),
                ('email_us', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('emails', models.TextField(max_length=500)),
                ('phones', models.TextField(max_length=100)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('tw_link', models.URLField(blank=True, null=True)),
                ('yt_link', models.URLField(blank=True, null=True)),
                ('app_description', models.CharField(blank=True, max_length=300, null=True)),
                ('android_app', models.URLField(blank=True, null=True)),
                ('ios_app', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
